# serve_addr: 127.0.0.1:11434
# model: deepseek-r1:1.5b
highlight: true

clients: # For any platform compatible with OpenAI's API
  - type: openai-compatible
    name: ollama
    api_base: http://localhost:11434/v1
#    api_key: xxx                                      # Optional
    models:
      - name: deepseek-r1:1.5b
        max_input_tokens: 131072
#      - name: llama3.1
#        max_input_tokens: 128000
#        supports_function_calling: true
#      - name: llama3.2-vision
#        max_input_tokens: 131072
#        supports_vision: true
#      - name: nomic-embed-text
#        type: embedding
#        default_chunk_size: 1000
#        max_batch_size: 50
